const data = [
  {
    username: 'hundohundohundohundohundohundoh',
    id: '1',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 2,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'extremelyes@gmail.com',
    id: '3',
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: '4',
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'y',
    id: 5000,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'errorRow',
  },
  {
    username: 'firstemperor@empire.com',
    id: 6,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'luckyheir@romans.com',
    id: 7,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'extremelylongem@gmail.com',
    id: 8,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'egg@example.com',
    id: 9,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'firstemperor@empire.com',
    id: 10,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 11,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'luckyheir@romans.com',
    id: 12,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'extremelylongeines@gmail.com',
    id: 13,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 14,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 15,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'firstemperor@empire.com',
    id: 17,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'luckyheir@romans.com',
    id: 18,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extrgetotwolines@gmail.com',
    id: 19,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 20,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'firstemperor@empire.com',
    id: 21,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'firstemperor@empire.com',
    id: 22,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
    rowType: 'duplicateRow',
  },
  {
    username: 'luckyheir@romans.com',
    id: 23,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremewolines@gmail.com',
    id: 24,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 25,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 26,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 27,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 28,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremelylongnes@gmail.com',
    id: 29,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 30,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 31,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: '32',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: '33',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremelytotwolines@gmail.com',
    id: 34,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 35,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 36,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'yay Let me tuse I want to test this break-word ',
    id: '37',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'extremewolines@gmail.com',
    id: '38',
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: '39',
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: '40',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 41,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 42,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremelylongnes@gmail.com',
    id: '43',
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: '44',
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 45,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 46,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremelytotwolines@gmail.com',
    id: 47,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 48,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 49,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'yay Let me tuse I want to test this break-word ',
    id: 50,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 51,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 52,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 53,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'extremelylongnes@gmail.com',
    id: 54,
    role: 'System Administrator, Administrator',
    status: 'Active',
    fullname: 'Sebastian Augustus',
  },
  {
    username: 'egg@example.com',
    id: 55,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 56,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'firstemperor@empire.com',
    id: 57,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'luckyheir@romans.com',
    id: 58,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Octavius Augustus',
  },
  {
    username: 'egg@example.com',
    id: null,
    role: 'System Administrator, NIH, Communications & Engagement Manager, Program Manager, Program Coordinator, Support Admin, Site Manager, Research Assistant, Administrator',
    status: 'Active',
    fullname: 'Constance Augustus',
  },
  {
    username: 'a',
    id: null,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'wipee',
    id: null,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'uuuuu',
    id: null,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'uuuu7979',
    id: null,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
  {
    username: 'sheshe',
    id: null,
    role: 'System Administrator',
    status: 'Active',
    fullname: 'Konstantin Augustus',
  },
];

export default data;
